#! /bin/bash

function poty(){
    DEFAULT_REPO="gitea"
    function poty_pub(){
        poetry version $1 && \
        poetry build && \
        poetry publish -r $DEFAULT_REPO 
    }
    versions=("patch" "minor" "major")
    if [[ "$1" == "pub" ]] ||
       [[ "$1" == "publish" ]]; then
        if [[ -z "$2" ]]; then
            poty_pub patch
        elif [[ "${versions[@]}" =~ "$2" ]]; then
            poty_pub "$2"
        else
            echo "error: invalid argument."
        fi
    elif [[ "$1" == "push" ]]; then
        if [[ -z "$2" ]]; then
            echo "error: expected an argument."
        else
            message="${@:2}"
            git add .
            git commit -m "$message"
            git push
        fi
    elif [[ "$1" == "i" ]] ||
         [[ "$1" == "ins" ]] ||
         [[ "$1" == "install" ]]; then
        poetry lock
        poetry install
    elif [[ "$1" =~ *.py ]]; then
        poetry run python3 $1
    else
        poetry "$@"
    fi
}
